db:
  mongo:
    uri: 'mongodb://0.0.0.0:27017'
    database: 'dev'
    collections:
      ranked_profiles: 'arena_ranked_profiles'
  redis:
    uri: 'redis://0.0.0.0:6379'

locations:
  spawn:
    x: 0.0
    y: 100.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
    world: 'world'
  editor:
    x: 0.0
    y: 100.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
    world: 'world'